### ISSUE TITLE
App should be signed otherwise it cannot be launched on macOS

### ISSUE THREAD

**Issue by joelgetaction** [skevy/graphiql-app#133] opened 2018-10-21 19:09 UTC
Nice app!  Thanks for your hard work on this.

Trying to launch the app results in `"GraphiQL.app" can't be opened because it is from an unidentified developer".  This happens because the app isn't properly signed with an Apple developer signature.  In many environments, "System Preferences => Security & Privacy => Allow apps downloaded from: App Store and identified developers" is the least secure setting allowed, so suggesting to turn this off is not a workaround.  This app should be properly signed so that anybody can launch it.  :-)

<img width="422" alt="screen shot 2018-10-21 at 12 04 55 pm" src="https://user-images.githubusercontent.com/40219063/47271114-19068300-d52a-11e8-9134-70c404833494.png">

**Comment by gjtorikian** [comment] 2018-10-22 12:09
Duplicate of https://github.com/skevy/graphiql-app/issues/130

**Closed by gjtorikian** 2018-10-22 12:09 UTC

**Comment by harsha-sagar** [comment] 2019-01-30 06:46
@gjtorikian 
installed using `brew cask`, still seeing same issue.

**Comment by justin-gardiner** [comment] 2019-06-18 13:06
same for me today

**Comment by davydhong** [comment] 2019-08-02 21:55
tried brew cask - can't open still.
Has anyone figured out how?

**Comment by marunk20** [comment] 2020-03-10 08:23
same for me today .. installed using `brew cask` .. but still getting the same error

**Comment by chiholiu** [comment] 2020-10-21 11:43
Just go to Finder -> Application -> Right click -> Open. Thank me later 👍

**Comment by emeka-vin** [comment] 2022-03-24 13:00
Thanks @chiholiu10 It worked

**Comment by dimitur2204** [comment] 2023-01-22 01:24
@chiholiu10 Nice

**Comment by Husban2030** [comment] 2023-02-08 13:12
> تطبيق جميل! شكرا لعملكم الشاق في هذا
> 
> محاولة تشغيل التطبيق يؤدي إلى تعذر فتح "GraphiQL.app" لأنه من مطور مجهول ". يحدث هذا بسبب عدم توقيع التطبيق بشكل صحيح مع توقيع مطور Apple. في العديد من البيئات ،" تفضيلات النظام => الأمان والخصوصية => السماح بالتطبيقات التي تم تنزيلها من: App Store والمطورين المحددين "هو الإعداد الأقل أمانًا المسموح به ، لذا فإن اقتراح إيقاف تشغيل هذا ليس حلاً. يجب توقيع هذا التطبيق بشكل صحيح حتى يمكن لأي شخص تشغيله.: -)
> 
> <img alt="لقطة شاشة 2018-10-21 الساعة 12 04 55 مساءً" width="422" src="https://user-images.githubusercontent.com/40219063/47271114-19068300-d52a-11e8-9134-70c404833494.png">

**Comment by Husban2030** [comment] 2023-02-08 13:12
hussain2022a حسين المنهالي

**Comment by mr-fixit** [comment] 2024-07-25 12:20
on macOS Sonoma, the above didn't work.

i tried the following (from [here](https://support.apple.com/en-us/102445))
- after trying to open and getting the system's "no" 
- go to system settings > privacy and security
- scroll down to find the 'open anyway' button
<img width="459" alt="image" src="https://github.com/user-attachments/assets/05e5c02b-d6eb-4846-82da-01448d62dbe3">

- clicked button, authenticated with admin account
... still didn't work.

then i saw "* These settings might not be available if your Mac is managed by a system administrator or IT department.", which applies to me.

ymmv.
