### ISSUE TITLE
TypeError on launch in 0.6.1

### ISSUE THREAD

**Issue by zeke** [skevy/graphiql-app#90] opened 2017-10-21 04:16 UTC
Hi, GraphQL folks!

I just downloaded GraphiQL for the first time on this computer, and here's what I see on first run:

![screen shot 2017-10-20 at 9 11 34 pm](https://user-images.githubusercontent.com/2289/31847964-c56821cc-b5db-11e7-9e0b-3f23e9e5d6e1.png)

```
TypeError: Failed to fetch
    at TypeError (native)
    at e.graphQLFetcher (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:23:29032)
    at t.value (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:26:29129)
    at t.value (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:26:22695)
    at e.notifyAll (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:7:12508)
    at r.close (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:23:4786)
    at r.closeAll (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:7:15916)
    at r.perform (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:7:15405)
    at u (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:23:22899)
    at r.perform (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:7:15322)
```

```
$ uname -a
Darwin Zekes-MBP 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

**Comment by zeke** [comment] 2017-10-21 04:17
First time I installed with `brew cask install graphiql`, then tried re-installed from the DMG GitHub release. Same result.

**Comment by gjtorikian** [comment] 2017-10-24 16:12
Dupe of #82, closed by https://github.com/skevy/graphiql-app/pull/93

**Closed by gjtorikian** 2017-10-24 16:12 UTC

**Comment by zeke** [comment] 2017-10-24 22:34
Thanks for the quick fix, @gjtorikian!

**Comment by linpekka** [comment] 2018-11-21 11:39
I still get these errors when installing from brew
